### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by nlepage** [Zenika/deadoralive#1]
Il faudrait que l'appli scale mieux sur les différentes tailles de device.

**Comment by mcampourcy** [comment]
J'embarque, je veux jouer sur mon tel :smile:

**Comment by nlepage** [comment]
Le device principale sera surement une tablette.
Par contre attention faut @stephanecohan va probablement nous proposer un nouveau design, donc il faut voir avec lui.
Si tu fais qqchose, ce serait bien qu'on ne le recasse pas ensuite pour le nouveau design.
