### ISSUE TITLE
Difficulté "Hard"

### ISSUE THREAD

**Issue by nlepage** [Zenika/deadoralive#10]
En difficulté "Hard":
 - Inverser les boutons "Dead" et "Alive" aléatoirement
 - Inverser les couleurs des boutons "Dead" et "Alive" aléatoirement
 - Changer les libellés des boutons "Dead" et "Alive", exemples:
   - "Still not dead"
   - "Not alive anymore"

**Comment by patou** [comment]
Donner moins de temps  ?

Mais multiplier le score par x.

**Comment by pyaillet** [comment]
- [ ] Inverser les boutons "Dead" et "Alive" aléatoirement
- [ ] Inverser les couleurs des boutons "Dead" et "Alive" aléatoirement
- [ ] Changer les libellés des boutons "Dead" et "Alive", exemples:
  - "Still not dead"
  - "Not alive anymore"
