### ISSUE TITLE
Amélioration design

### ISSUE THREAD

**Issue by nlepage** [Zenika/deadoralive#2]
Il faut que ce soit plus joli !

**Comment by nlepage** [comment]
Desgin proposé par @stephanecohan:
https://pkbdxa.axshare.com/#id=wlsvxk&p=doa

**Comment by patou** [comment]
@stephanecohan Comment on récupére les images, et on accède au CSS ?

**Comment by patou** [comment]
Merci @stephanecohan

**Comment by mcampourcy** [comment]
@patou je pensais m'occuper de l'intégration de la maquette (cf la PR sur le responsive), si c'est ok pour toi :)

**Comment by patou** [comment]
J'ai commencé à faire l'intégration 👍 

https://github.com/Zenika/deadoralive/pull/37

Tu peux reprendre et continuer.
