### ISSUE TITLE
Stocker le nom et l'email

### ISSUE THREAD

**Issue by patou** [Zenika/deadoralive#29]
Pour l'instant, le nom et l'email demandé pour jouer ne servent pas.

Il faudrait les stocker dans le firebase.
Gérer une option pour accepter de garder les informations personnels et de pouvoir les recontacter.

**Comment by nlepage** [comment]
Oui, je pense qu'on peut le faire au même moment que l'enregistrement du score cf #7

**Comment by patou** [comment]
Mais il faut valider le RGPD, demander si le joueur souhaite partager son score et son nom et email.

**Comment by nlepage** [comment]
Tout à fait il faut consulter @Mayie

**Comment by nlepage** [comment]
fixed by #35
