### ISSUE TITLE
Mentions légales et cookies

### ISSUE THREAD

**Issue by Mayie** [Zenika/deadoralive#39]
Faire une page mentions légales et mettre un lien vers https://foundation.wikimedia.org/wiki/Cookie_statement

**Comment by Mayie** [comment]
**Mentions Légales**
Zenika SAS de conseil en systèmes et logiciels informatiques.
10 rue de Milan 75009 Paris
Capital de 130 000 euros
RCS : Paris B 489 682 005

Créé en 2006, Zenika est un cabinet d'innovation technologique, managériale et organisationnelle, qui accompagne les entreprises dans leur transformation numérique. Zenika fait le lien entre le monde organique et le monde numérique et se positionne comme un "One Stop Shop"​ pour ses clients. 

Depuis l'interface (Web, Mobile, Voix, Objet Connecté, RA/RV) jusqu'à la data et son usage, le tout en mode agile, Zenika regroupe des profils variés sur les domaines d'expertise suivants : Java, Big Data, Web, Mobilité, IoT, DevOps, Craftsmanship, Agilité, sécurité et transformation des organisations. Après les ouvertures successives des agences de Paris, Lyon, Rennes, Nantes, Lille, Bordeaux, Singapour et Montréal, le groupe souhaite renforcer son rayonnement national et international. 

Directeur de publication : Carl Azoury, CEO Zenika
Hébergement :
Firebase

**Propriété Intellectuelle**
La structure générale, les textes, images animées ou non, les savoir-faire, les programmes et logiciels ainsi que tout autre élément composant ce site sont la propriété exclusive de Zenika et sont protégés par le droit d’auteur. Toute représentation totale ou partielle de ce site, par quelque procédé que ce soit, sans l’autorisation expresse de Zenika est donc interdite et constituerait une contrefaçon. Il en est de même des bases de données figurant sur le site training.zenika.com qui sont protégées.
Les marques, les noms commerciaux, les logos figurant sur ce site sont des marques déposées de Zenika sauf mention contraire. Toute reproduction totale ou partielle des marques ou logos, effectuée à partir des éléments du site et sans l’autorisation de Zenika est donc prohibée.

**Conditions d’utilisation**
Tout lien avec ce site doit faire l’objet d’une autorisation préalable écrite de Zenika et ne pourra être réalisé que vers l’adresse de la page d’accueil du site www.zenika.com avec l’intégration d’un logo.
Malgré les soins apportés par Zenika, les informations contenues dans ce site sont données à titre indicatif et sont sujettes à changement sans préavis. En conséquence, l’utilisateur reconnaît utiliser ces informations sous sa responsabilité exclusive.
Il accepte les présentes conditions d’utilisation. Tout litige portant sur l’interprétation ou l’exécution des présentes mentions sera de la compétence exclusive des tribunaux français faisant l’application de la loi française. L’ensemble des éléments de ce site est protégé par copyright Zenika.

**Cookies**
https://foundation.wikimedia.org/wiki/Cookie_statement

**Transmission des données**
Lorsque vous nous fournissez vos données afin d’être recontacté par nos services, celles-ci sont traitées uniquement par le personnel interne et habilité de Zenika et ne font l’objet d’aucune transmission à des tiers extérieurs.

**Vos droits**
Vous disposez d’un droit d’accès aux données vous concernant ou pouvez demander leur effacement. Vous disposez également d’un droit d’opposition pour motif légitime, d’un droit de rectification, de portabilité et d’un droit à la limitation du traitement de vos données (cf. cnil.fr pour plus d’informations sur vos droits).
Pour exercer ces droits ou pour toute question sur le traitement de vos données, vous pouvez contacter notre Délégué à la protection des données (DPO) :
Par email : mydata@zenika.com
Par voie postale : 10 rue de Milan 75009 Paris
Lorsque vous exercez vos droits, vous devrez nous fournir une preuve de votre identité. A défaut nous ne serons pas en mesure de traiter votre demande et nous nous réservons le droit de ne pas faire droit à votre demande.
Si vous estimez après nous avoir contactés que vos droits ne sont pas respectés, vous pourrez à tout moment saisir l’autorité de contrôle.

**Sécurité**
Notre préoccupation est de préserver la qualité et l’intégrité de vos données personnelles. Les technologies ainsi que les politiques de sécurité appliquées par nous-mêmes et nos prestataires techniques permettent de protéger vos données contre tout accès non autorisé, toute altération, toute destruction malveillante ou accidentelle et toute perte involontaire de données. Nous améliorons sans cesse nos procédures de sécurité au fur et à mesure de l’évolution des technologies afin de maintenir un niveau de protection maximum. Notre personnel et celui de nos sous-traitants ayant accès aux données personnelles sont soumis contractuellement à une obligation de confidentialité.

**Comment by nlepage** [comment]
Adresse pour l'hébergement Firebase:
1600 Amphitheatre Parkway, Mountain View, California 94043, United States,

**Comment by mcampourcy** [comment]
@stephanecohan Une idée d'où placer le lien sur la page d'accueil ? :sweat_smile:

**Comment by Mayie** [comment]
> 
> 
> Pour les cookies, je pense que cela n'a pas de besoin pour ce projet :
> La connexion sera uniquement lié à zenika.com et fait par les responsables du stand sur la tablette de jeu pour éviter que des gens jouent au jeux sans venir sur le stand.
> 
> Si on accède à l'application sans être connecté avec un compte zenika.com, il n'y a aucune sauvegarde de données.

Je préfère qu'on se protège complétement au cas ou l'application est réutilisée. 
On a des cookies à cause de Wikipédia uniquement.

**Comment by Mayie** [comment]
En bas à gauche ça serait pas mal, c'est ce qui se fait en général.

**Comment by Mayie** [comment]
> 
> 
> @stephanecohan Une idée d'où placer le lien sur la page d'accueil ? 😅

En bas à gauche ou en bas centré ça serait pas mal, c'est ce qui se fait en général.
