### ISSUE TITLE
Point  sur le nouveau design

### ISSUE THREAD

**Issue by patou** [Zenika/deadoralive#48]
Voici quelques points que j'ai remarqué sur le nouveau design : 

* Les images, n'ont pas le même ratio et cela décale les boutons, et cela changent ensemble de l'écriture.
* L'image des boutons dead or alive, ne suit pas les boutons dans le mode hard
* La barre de progression devrait être inversé, Elle commence à 100% et réduit.

**Comment by mcampourcy** [comment]
@patou Tu as fait les tests sur quel navigateur et quelle résolution ? C'est directement sur la tablette ?
Normalement, les images ont toutes une taille fixe, c'est chelou le décalage 🤔 
Je vais checker pour le mode hard.
Pour la barre de progression, c'est non faisable avec les éléments HTML. Si besoin, je peux coder un truc pour avoir un équivalent.

**Comment by nlepage** [comment]
Avec la tablette recrutement:
![Screenshot_20191014-084937](https://user-images.githubusercontent.com/19571875/66733680-9aa0a080-ee60-11e9-8d75-52453e079260.png)
![Screenshot_20191014-085733](https://user-images.githubusercontent.com/19571875/66733770-dd627880-ee60-11e9-9488-e1884e8b046d.png)
![Screenshot_20191014-085747](https://user-images.githubusercontent.com/19571875/66733778-ea7f6780-ee60-11e9-8329-80f222939e09.png)
![Screenshot_20191014-085759](https://user-images.githubusercontent.com/19571875/66733787-f1a67580-ee60-11e9-85ca-8a3a1e74cc1a.png)

**Comment by nlepage** [comment]
Faire abstraction du machin de volume de sonnerie, c'est parce que j'ai du mal à prendre des screenshots avec la tablette de :hankey:

**Comment by patou** [comment]
@mcampourcy Je reproduit plus pour les images.

Pour la barre de progression, c'est juste d'inverser la progression, commencer par 100% et réduire.

Et autre point : 
lorsque l'on clique sur un bouton il devient actif avec une surbrillance.
Mais lorsque l'on passe à la rockstar suivante, le bouton actif soit réinitialisé.

**Comment by mcampourcy** [comment]
@patou j'ai bien compris pour la barre de progression, le truc c'est qu'on utilise un élément HTML natif qui ne prend pas en compte ce mode de fonctionnement inverse. Je peux tout à fait faire une autre barre de progression avec du CSS et un morceau de JS, ça va juste demander un tout petit peu de temps de le faire puisqu'il faut le reprendre de zéro.

Ok pour le bouton, c'est le focus qui ne s'en va pas.

@nlepage Le rendu est cool ! C'est pris sur Chrome ? Tu as moyen de savoir si c'est la toute dernière version ?

Du coup, en fix, je note :

- [ ] La progress bar qui flotte au milieu des scores
- [ ] Le bouton qui garde le focus
- [ ] Regarder le temps que prendrait une nouvelle progress bar

Vous voyez autre chose ?

**Comment by pyaillet** [comment]
En difficulty hard, le texte changeant fait que les boutons n'ont pas la même taille.
<img width="1438" alt="Capture d’écran 2019-10-14 à 17 14 01" src="https://user-images.githubusercontent.com/11957179/66762327-1113c180-eea6-11e9-95ac-9aa2eaad1b5d.png">
