### ISSUE TITLE
Ajouter firebase auth

### ISSUE THREAD

**Issue by nlepage** [Zenika/deadoralive#6]
Que l'appli ne soit accessible que avec un compte @zenika.com

**Comment by patou** [comment]
Pourquoi ?

**Comment by nlepage** [comment]
Les gens vont jouer sur une tablette sur le stand.
Et l'idée c'est qu'il n'y ait pas un petit malin qui pique l'URL et se connecte depuis son PC...
Après je suis peut être parano...

**Comment by nlepage** [comment]
Bidouiller pour envoyer des faux scores.
