### ISSUE TITLE
Stocker scores

### ISSUE THREAD

**Issue by nlepage** [Zenika/deadoralive#7]
Enregistrer les scores dans firestore au moment du game over.

Activer le bouton "New Game" uniquement si le score a bien été enregistré.

**Comment by nlepage** [comment]
Règles pour rejouer:
 - On autorise les gens à rejouer autant qu'ils veulent
 - Dans le classement, on ne prend en compte que les 3 premières participations

**Comment by patou** [comment]
> En conséquence, sur l'écran d'accueil il faudrait d'abord demander l'email, et si on le connait déjà on ne redemande pas les autres infos.

En l’occurrence, comme on demande que le name et l'email, rien de très complexe.

**Comment by nlepage** [comment]
fixed by #35
